---
# fetch OULibraries.centos7 from github
- src: https://github.com/OULibraries/ansible-role-centos7
  version: master
  name: OULibraries.centos7
# fetch OULibraries.apache2 from github
- src: https://github.com/OULibraries/ansible-role-apache2
  version: master
  name: OULibraries.apache2
