---

- src: https://github.com/OULibraries/ansible-role-centos7
  version: master
  name: OULibraries.centos7

- src: https://github.com/OULibraries/ansible-role-apache2
  version: master
  name: OULibraries.apache2

- src: https://github.com/OULibraries/ansible-role-mariadb
  version: master
  name: OULibraries.mariadb

- src: https://github.com/OULibraries/ansible-role-users
  version: master
  name: OULibraries.users
