---
# fetch jsnshrmn.centos7 from github
- src: https://github.com/OULibraries/ansible-role-centos7
  version: master
  name: jsnshrmn.centos7
# fetch jsnshrmn.mariadb from github
- src: https://github.com/OULibraries/ansible-role-mariadb
  version: master
  name: jsnshrmn.mariadb
# fetch jsnshrmn.apache2 from github
- src: https://github.com/OULibraries/ansible-role-apache2
  version: master
  name: jsnshrmn.apache2
