---
- name: Ensure /opt/d7/bin exists
  file:
    path: /opt/d7/bin
    state: directory
    mode: 0655
    owner: root
    group: wheel
    recurse: yes

- name: scripts to /opt/d7/bin
  copy:
    src: "{{ item }}"
    dest: /opt/d7/bin/
    mode: 0755
    owner: root
    group: wheel
  with_items:
    - d7_cc.sh
    - d7_clean.sh
    - d7_composer.sh
    - d7_dump.sh
    - d7_httpd_conf.sh
    - d7_importdb.sh
    - d7_init.sh
    - d7_make.sh
    - d7_make_islandora.sh
    - d7_migrate.sh
    - d7_perms_fix.sh
    - d7_perms.sh
    - d7_restore.sh
    - d7_snapshot.sh
    - d7_sync.sh
    - d7_update.sh

- name: Install Drupal Apache includes
  template:
    src: "{{ item }}.j2"
    dest: "/opt/rh/httpd24/root/etc/httpd/conf.d/{{ item }}"
    mode: 0644
    owner: root
    group: wheel
  with_items:
    - drupal.include
    - drupal-files.include

- name:  Configure Apache MPM settings
  template:
    src:  00-mpm.conf.j2
    dest: /opt/rh/httpd24/root/etc/httpd/conf.modules.d/00-mpm.conf
    mode: 0644
    owner: root
    group: root

- name: Install cron scripts
  copy:
    src: "{{ item }}"
    dest: /etc/cron.daily/
    mode: 0755
    owner: root
    group: wheel
  with_items:
    - d7_daily.cron

- name: Ensure /opt/d7/etc exists
  file:
    path: /opt/d7/etc
    state: directory
    mode: 0655
    owner: root
    group: wheel
    recurse: yes

- name: Install httpd template file
  copy:
    src: d7_init_httpd_template
    dest: /opt/d7/etc/
    owner: apache
    group: wheel
    mode: 0444

- name: Install d7 default.settings.php
  copy:
    src: default.settings.php
    dest: /opt/d7/etc/
    owner: apache
    group: wheel
    mode: 0644

- name: Install d7 config
  template:
    src: d7_conf.sh.j2
    dest: /opt/d7/etc/d7_conf.sh
    owner: root
    group: wheel
    mode: 0444

- name: Install site wide config
  template:
    src: d7_host_config.inc.j2
    dest: /opt/d7/etc/d7_host_config.inc.php
    owner: apache
    group: wheel
    mode: 0444

- name: Install solr config
  template:
    src: d7_solr_config.inc.j2
    dest: /opt/d7/etc/d7_solr_config.inc.php
    owner: apache
    group: wheel
    mode: 0444
