---
- name: Ensure /tmp/downloads exists
  file:
    path: /tmp/downloads
    owner: root
    group: root
    state: directory

- name: Ensure php dir exists
  file:
    path: /opt/php
    owner: libacct
    group: wheel
    state: directory

- name: Ensure php/bin path exists
  file:
    path: /opt/php/bin
    owner: libacct
    group: wheel
    state: directory

- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/downloads/composer-installer.php
    mode: 0775

- name: Install Composer
  become: yes
  become_user: libacct
  command: >
    php /tmp/downloads/composer-installer.php
  args:
    chdir: /opt/php/bin
    creates: /opt/php/bin/composer.phar

- name: Make sure Composer is executable
  file:
    path: /opt/php/bin/composer.phar
    owner: libacct
    group: wheel
    mode: 0775

- name: Composer install Drush 7
  become: yes
  become_user: libacct
  shell: |
    /opt/php/bin/composer.phar init --require=drush/drush:7.* -n
    /opt/php/bin/composer.phar config bin-dir /opt/php/bin
    /opt/php/bin/composer.phar install
  args:
    chdir: /opt/php
    creates: /opt/php/bin/drush

- name: Ensure /etc/profile.d/drush.sh exists
  file:
    path: /etc/profile.d/drush.sh
    state: touch
    mode: 0644
    owner: root
    group: wheel

- name: Add drush scripts to path
  lineinfile:
    state: present
    dest: /etc/profile.d/drush.sh
    line: "export PATH=/opt/php/bin:$PATH"

- name: Set up bash completion for drush
  file:
    src: /opt/php/vendor/drush/drush/drush.complete.sh
    dest: /etc/bash_completion.d/drush.complete.sh
    state: link
