---
- name: Set SELinux exceptions for apache
  command: "setsebool -P {{ item }} on"
  with_items:
    - httpd_can_connect_ldap
    - httpd_can_network_connect
    - httpd_can_sendmail

- name: Allow apache group to view httpd log files
  file:
    path: /var/log/httpd
    owner: root
    group: apache
    mode: 0750
- name: Add /srv config include to http.conf
  lineinfile:
    state: present
    dest: /etc/httpd/conf/httpd.conf
    line: "IncludeOptional \"/srv/*/etc/*.conf\""

- name: Ensure /etc/profile.d/d7-ops.sh exists
  file:
    path: /etc/profile.d/d7-ops.sh
    state: touch
    mode: 0644
    owner: root
    group: root
- name: Add ops scripts to path
  lineinfile:
    state: present
    dest: /etc/profile.d/d7-ops.sh
    line: "export PATH=/opt/d7/bin:$PATH"

- name: Configure Apache for PHP-FPM
  copy:
    src: php-fpm.conf
    dest: /etc/httpd/conf.d/php-fpm.conf
    mode: 0644
    owner: root
    group: root

- name: Configure Zend OpCache for SCL PHP
  template:
    src: 10-opcache.ini.j2
    dest: /etc/opt/rh/rh-php56/php.d/10-opcache.ini
    mode: 0644
    owner: root
    group: root

- name: Restart PHP-FPM service to detect new libraries, config
  service:
    name: rh-php56-php-fpm
    state: restarted
