---
- name: Set SELinux exceptions for apache
  command: "setsebool -P {{ item }} on"
  with_items:
  - httpd_can_connect_ldap
  - httpd_can_network_connect
  - httpd_can_sendmail
- name: Allow apache group to view httpd log files
  file:
    path: /var/log/httpd
    owner: root
    group: apache
    mode: 0750
- name: Add config include to http.conf
  lineinfile:
    state: present
    dest: /etc/httpd/conf/httpd.conf
    line: "IncludeOptional \"/srv/*/etc/*.conf\""
- name: Set APC Username
  replace:
    dest: /usr/share/pear/apc.php
    regexp: >
      ^defaults\('ADMIN_USERNAME','apc'\);(.*)$
    replace: >
      defaults('ADMIN_USERNAME','{{ apc_username }}');\1
- name: Set APC Password
  replace:
    dest: /usr/share/pear/apc.php
    regexp: >
      ^defaults\('ADMIN_PASSWORD','password'\);(.*)$
    replace: >
      defaults('ADMIN_PASSWORD','{{ apc_password }}');\1

- name: Copy apc_clear.php
  copy:
    src: apc_clear.php
    dest: /usr/share/pear
    mode: 0754
    owner: root
    group: wheel

- name: Set upload_max_filesize
  replace:
    dest: /etc/php.ini
    regexp: >
      ^upload_max_filesize = 2M$
    replace: "upload_max_filesize = 64M"
- name: Set post_max_size
  replace:
    dest: /etc/php.ini
    regexp: >
      ^post_max_size = 8M$
    replace: "post_max_size = 70M"
- name: Ensure /etc/profile.d/d7-ops.sh exists
  file:
    path: /etc/profile.d/d7-ops.sh
    state: touch
    mode: 0644
    owner: root
    group: root
- name: Add ops scripts to path
  lineinfile: 
    state: present
    dest: /etc/profile.d/d7-ops.sh
    line: "export PATH=/opt/d7/bin:$PATH"
- name: Add ops scripts to sudo secure_path
  replace:
    dest: /etc/sudoers
    regexp: >
      ^Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin$
    replace: 'Defaults    secure_path = /opt/d7/bin:/sbin:/bin:/usr/sbin:/usr/bin'
    validate: visudo -cf %s
