---
- name: Ensure /tmp/downloads exists
  file:
    path: /tmp/downloads
    owner: root
    group: root
    state: directory

- name: Ensure /opt/php exists
  file:
    path: /opt/php
    owner: root
    group: wheel
    state: directory

- name: Ensure composer directory exists.
  file:
    path: /opt/php/composer
    owner: root
    group: wheel
    state: directory

- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/downloads/composer-installer.php
    mode: 0755

- name: Run Composer installer.
  command: >
    php /tmp/downloads/composer-installer.php
  args:
    chdir: /opt/php/composer
    creates: /opt/php/composer/composer.phar

- name: Download the Drush release
  get_url:
    url: https://github.com/drush-ops/drush/archive/7.3.0.zip
    dest: /tmp/downloads/7.3.0.tar.gz
    mode: 0655

- name: Unarchive Drush release
  unarchive:
    src: /tmp/downloads/7.3.0.tar.gz
    dest: /opt/php/
    remote_src: yes

- name: Composer install drush requirements
  command: >
    /opt/php/composer/composer.phar install
  args:
    chdir: /opt/php/drush-7.3.0

- name: Symbolic link to versioned drush folder
  file:
    src: /opt/php/drush-7.3.0
    dest: /opt/php/drush
    state: link
    owner: root
    group: wheel

- name: Ensure /etc/profile.d/drush.sh exists
  file:
    path: /etc/profile.d/drush.sh
    state: touch
    mode: 0644
    owner: root
    group: wheel

- name: Add drush scripts to path
  lineinfile: 
    state: present
    dest: /etc/profile.d/d7-ops.sh
    line: "export PATH=/opt/php/drush:$PATH"

- name: Set up bash completion for drush
  file:
    src: /opt/php/drush/drush.complete.sh
    dest: /etc/bash_completion.d/drush.complete.sh
