---
- name: Install yum packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - php
  - mod_php
  - php-devel
  - php-mysql
  - php-ldap
  - php-pear
  - php-gd
  - php-drush-drush
  - mariadb
  - gcc
- name: Install PEAR packages
  pear: 
    name: "{{ item }}"
    state: present
  with_items:
  - Console_Table
  - pecl/apc
- name: Set SELinux exceptions for apache 
  command: "setsebool -P {{ item }} on"
  with_items:
  - httpd_can_connect_ldap
  - httpd_can_network_connect
  - httpd_can_sendmail
- name: Add config include to http.conf
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    line: "IncludeOptional \"/srv/*/etc/*.conf\""
- name: Set APC Username
  lineinfile:
    dest: /usr/share/pear/apc.php
    regexp: ^defaults\('ADMIN_USERNAME','apc'\);
    line: "defaults('ADMIN_USERNAME','{{ apc_username }}');"
- name: Set APC Password
  lineinfile:
    dest: /usr/share/pear/apc.php
    regexp: ^defaults\('ADMIN_PASSWORD','password'\);
    line: "defaults('ADMIN_PASSWORD','{{ apc_password }}');"
- name: Ensure /etc/profile.d/d7-ops.sh exists
  file:
    path: /etc/profile.d/d7-ops.sh
    state: touch
    mode: 0644
    owner: root
    group: root
- name: Add ops scripts to path
  lineinfile: "dest=/etc/profile.d/d7-ops.sh line='export PATH=/opt/d7/bin:$PATH'"
- name: Add ops scripts to sudo secure_path
  lineinfile: "dest=/etc/sudoers state=present regexp='^Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin$' line='Defaults    secure_path = /opt/d7/bin:/sbin:/bin:/usr/sbin:/usr/bin' validate='visudo -cf %s'"
