---
- name: Install packages necessary to run Drupal
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - php
  - mod_php
  - php-mysql
  - php-ldap
  - php-pear
  - php-gd
  - php-drush-drush
  - mariadb

- name: Add httpd template file
  copy:
    src: d7_init_httpd_template
    dest: /opt/d7/etc

- name: Ensure /opt/d7/bin exists
  file:
    path: /opt/d7/bin
    state: directory
    mode: 0655
    owner: root
    group: wheel
    recurse: yes

- name: scripts to /opt/d7/bin
  copy:
    src: "{{ item }}"
    dest: /opt/d7/bin/
    mode: 0754
    owner: root
    group: wheel
  with_items:
      - d7_init.sh
      - d7_make.sh
      - d7_sync.sh
      - d7_clean.sh
      - d7_httpd_conf.sh
      - d7_update.sh
      - d7_dump.sh
  tags:
    scripts

- name: Ensure /opt/d7/etc exists
  file:
    path: /opt/d7/etc
    state: directory
    mode: 0655
    owner: root
    group: wheel
    recurse: yes

- name: Add ops config
  template:
    src: d7-conf.sh.j2
    dest: /opt/d7/etc/d7-conf.sh
    owner: root
    group: wheel
    mode: 0444
    
- name: Ensure /etc/profile.d/d7-ops.sh exists
  file:
    path: /etc/profile.d/d7-ops.sh
    state: touch
    mode: 0644
    owner: root
    group: root
- name: Add ops scripts to path
  lineinfile: "dest=/etc/profile.d/d7-ops.sh line='export PATH=/opt/d7/bin:$PATH'"
- name: Add ops scripts to sudo secure_path
  lineinfile: "dest=/etc/sudoers state=present regexp='^Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin$' line='Defaults    secure_path = /opt/d7/bin:/sbin:/bin:/usr/sbin:/usr/bin' validate='visudo -cf %s'"

- name: Ensure temp dir exists
  file:
    path: "{{ temp_dir }}"
    state: directory
    mode: 0770
    owner: root
    group: wheel
    recurse: yes
