---
- include: yum.yml
  sudo: yes

- include: pear.yml
  sudo: yes

- include: configure.yml
  sudo: yes

- include: composer.yml
  sudo: yes
  tags: composer

- include: assets.yml
  sudo: yes
  tags: assets
