---
- include: yum.yml
  become: true

- include: pear.yml
  become: true

- include: configure.yml
  become: true

- include: composer.yml
  become: true
  tags: composer

- include: assets.yml
  become: true
  tags: assets
