---
- name: Install yum packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb
    - gcc

- name: Make sure some packages are removed
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - drush
    - php
    - httpd
