---
- name: Install yum packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - php
    - mod_php
    - php-devel
    - php-mysql
    - php-ldap
    - php-pear
    - php-gd
    - php-soap
    - php-mbstring
    - php-pear-CAS
    - mariadb
    - gcc

- name: Make sure some packages are removed
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - drush
